services:
  nginx:
    image: nginx:alpine
    container_name: hk_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
    networks:
      - web_network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: hk_db
    environment:
      - POSTGRES_USER=raulkiyoshi
      - "POSTGRES_PASSWORD=Ghb260829cb132!"
      - POSTGRES_DB=raulkiyoshi
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web_network
    restart: always

  server:
    build: ./server
    environment:
      - "DATABASE_URL=postgresql://raulkiyoshi:Ghb260829cb132!@db:5432/raulkiyoshi?schema=public"
      - "JWT_SECRET=Theojunji1!"
      - PORT=3333
    depends_on:
      - db
    networks:
      - web_network
    restart: always

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - web_network
    restart: always

networks:
  web_network:
    name: hk_web_network

volumes:
  db_data:
