services:
  nginx:
    image: nginx:alpine
    container_name: hk_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - client
      - server
    networks:
      - web_network
    restart: always

  certbot:
    image: certbot/certbot
    container_name: hk_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - web_network

  db:
    image: postgres:15-alpine
    container_name: hk_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web_network
    restart: always

  server:
    build: ./server
    environment:
      - "DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public"
      - "JWT_SECRET=${JWT_SECRET}"
      - PORT=3333
    depends_on:
      - db
    networks:
      - web_network
    restart: always

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - web_network
    restart: always

networks:
  web_network:
    name: hk_web_network

volumes:
  db_data:
