services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@vidatodarevisao.com.br"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: always
    labels:
      - "traefik.enable=true"
      # Global HTTP -> HTTPS Redirect
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  db:
    image: postgres:15-alpine
    container_name: hk_db
    environment:
      - POSTGRES_USER=raulkiyoshi
      - "POSTGRES_PASSWORD=Ghb260829cb132!"
      - POSTGRES_DB=raulkiyoshi
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  server:
    build: ./server
    environment:
      - "DATABASE_URL=postgresql://raulkiyoshi:Ghb260829cb132!@db:5432/raulkiyoshi?schema=public"
      - "JWT_SECRET=Theojunji1!"
      - PORT=3333
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      # Router for API (HTTPS)
      - "traefik.http.routers.server.rule=Host(`vidatodarevisao.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
      - "traefik.http.services.server.loadbalancer.server.port=3333"
    restart: always

  client:
    build: ./client
    depends_on:
      - server
    labels:
      - "traefik.enable=true"
      # Router for Client (HTTPS)
      - "traefik.http.routers.client.rule=Host(`vidatodarevisao.com.br`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
      - "traefik.http.services.client.loadbalancer.server.port=80"
    restart: always

volumes:
  db_data:
